name: root_inn
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flustars: ^0.2.6            # Flutter常用工具类库
  dio: ^2.1.0
  rxdart: ^0.21.0
  cached_network_image: ^1.1.1
  screen: ">=0.0.4 <0.1.0"
  fluttertoast: ^3.1.0
  package_info: ^0.4.0+6
  flutter_staggered_grid_view: ^0.3.0
  tip_dialog: ^2.1.0
  webview_flutter: ^0.3.17

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/lotteryImgs/
  fonts:
    - family: pixel
      fonts:
        - asset: assets/fonts/FZXIANGSU12.TTF

  